/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalRouteImport } from './routes/rental'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as QuotingRouteImport } from './routes/quoting'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstoqueOmieRouteImport } from './routes/estoque-omie'
import { Route as ComandoRouteImport } from './routes/comando'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidoComandoTokenRouteImport } from './routes/pedido-comando.$token'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalRoute = RentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotingRoute = QuotingRouteImport.update({
  id: '/quoting',
  path: '/quoting',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRoute = FreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueOmieRoute = EstoqueOmieRouteImport.update({
  id: '/estoque-omie',
  path: '/estoque-omie',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandoRoute = ComandoRouteImport.update({
  id: '/comando',
  path: '/comando',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoComandoTokenRoute = PedidoComandoTokenRouteImport.update({
  id: '/pedido-comando/$token',
  path: '/pedido-comando/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approval': typeof ApprovalRoute
  '/comando': typeof ComandoRoute
  '/estoque-omie': typeof EstoqueOmieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/freight': typeof FreightRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/products': typeof ProductsRoute
  '/purchasing': typeof PurchasingRoute
  '/quoting': typeof QuotingRoute
  '/receipt': typeof ReceiptRoute
  '/rental': typeof RentalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/trips': typeof TripsRoute
  '/pedido-comando/$token': typeof PedidoComandoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approval': typeof ApprovalRoute
  '/comando': typeof ComandoRoute
  '/estoque-omie': typeof EstoqueOmieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/freight': typeof FreightRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/products': typeof ProductsRoute
  '/purchasing': typeof PurchasingRoute
  '/quoting': typeof QuotingRoute
  '/receipt': typeof ReceiptRoute
  '/rental': typeof RentalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/trips': typeof TripsRoute
  '/pedido-comando/$token': typeof PedidoComandoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approval': typeof ApprovalRoute
  '/comando': typeof ComandoRoute
  '/estoque-omie': typeof EstoqueOmieRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/freight': typeof FreightRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/maintenance': typeof MaintenanceRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/products': typeof ProductsRoute
  '/purchasing': typeof PurchasingRoute
  '/quoting': typeof QuotingRoute
  '/receipt': typeof ReceiptRoute
  '/rental': typeof RentalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/trips': typeof TripsRoute
  '/pedido-comando/$token': typeof PedidoComandoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/comando'
    | '/estoque-omie'
    | '/forgot-password'
    | '/freight'
    | '/login'
    | '/logs'
    | '/maintenance'
    | '/movimentacoes'
    | '/products'
    | '/purchasing'
    | '/quoting'
    | '/receipt'
    | '/rental'
    | '/reset-password'
    | '/services'
    | '/trips'
    | '/pedido-comando/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/comando'
    | '/estoque-omie'
    | '/forgot-password'
    | '/freight'
    | '/login'
    | '/logs'
    | '/maintenance'
    | '/movimentacoes'
    | '/products'
    | '/purchasing'
    | '/quoting'
    | '/receipt'
    | '/rental'
    | '/reset-password'
    | '/services'
    | '/trips'
    | '/pedido-comando/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/comando'
    | '/estoque-omie'
    | '/forgot-password'
    | '/freight'
    | '/login'
    | '/logs'
    | '/maintenance'
    | '/movimentacoes'
    | '/products'
    | '/purchasing'
    | '/quoting'
    | '/receipt'
    | '/rental'
    | '/reset-password'
    | '/services'
    | '/trips'
    | '/pedido-comando/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalRoute: typeof ApprovalRoute
  ComandoRoute: typeof ComandoRoute
  EstoqueOmieRoute: typeof EstoqueOmieRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FreightRoute: typeof FreightRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  ProductsRoute: typeof ProductsRoute
  PurchasingRoute: typeof PurchasingRoute
  QuotingRoute: typeof QuotingRoute
  ReceiptRoute: typeof ReceiptRoute
  RentalRoute: typeof RentalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TripsRoute: typeof TripsRoute
  PedidoComandoTokenRoute: typeof PedidoComandoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental': {
      id: '/rental'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quoting': {
      id: '/quoting'
      path: '/quoting'
      fullPath: '/quoting'
      preLoaderRoute: typeof QuotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight': {
      id: '/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof FreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-omie': {
      id: '/estoque-omie'
      path: '/estoque-omie'
      fullPath: '/estoque-omie'
      preLoaderRoute: typeof EstoqueOmieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comando': {
      id: '/comando'
      path: '/comando'
      fullPath: '/comando'
      preLoaderRoute: typeof ComandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-comando/$token': {
      id: '/pedido-comando/$token'
      path: '/pedido-comando/$token'
      fullPath: '/pedido-comando/$token'
      preLoaderRoute: typeof PedidoComandoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalRoute: ApprovalRoute,
  ComandoRoute: ComandoRoute,
  EstoqueOmieRoute: EstoqueOmieRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FreightRoute: FreightRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MaintenanceRoute: MaintenanceRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  ProductsRoute: ProductsRoute,
  PurchasingRoute: PurchasingRoute,
  QuotingRoute: QuotingRoute,
  ReceiptRoute: ReceiptRoute,
  RentalRoute: RentalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TripsRoute: TripsRoute,
  PedidoComandoTokenRoute: PedidoComandoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
